### ISSUE TITLE
Google Indexing

### ISSUE THREAD

**Issue by eokeeffe** [3dgeoinfo2021/3dgeoinfo2021.github.io#1]
So I've checked the index.html and the Google Verfification code is already there. 
We'll need to check in about 24 hours (21.23 hours on average but hey).

Everything looks ok, lets wait and see if it shows. 

TY Vu

**Comment by eokeeffe** [comment]
Ok the site is now being picked up when using all 4 terms.
3D geo info 2021

It'll require more keywords to get the site picked up for more search terms,

**Comment by 3dgeoinfo2021** [comment]
awesome, thank you
